apiVersion: v1
kind: Service
metadata:
  name: go-gin-service
spec:
  selector:
    app: go-gin
  ports:
    - protocol: "TCP"
      port: 1231
      targetPort: 1231
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-gin
spec:
  selector:
    matchLabels:
      app: go-gin
  replicas: 3
  template:
    metadata:
      labels:
        app: go-gin
    spec:
      containers:
        - name: go-app
          image: sean200365/gin-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 1231

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  labels:
    app: postgres-db
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  clusterIP: None
  selector:
    app: postgres-db

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
        - name: postgres-db
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: mysecretpassword
          ports:
            - containerPort: 5432
