apiVersion: v1
kind: Service
metadata:
  name: gin-server
spec:
  selector:
    app: go-gin
  ports:
    - protocol: "TCP"
      port: 1231
      targetPort: 1231
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-gin
spec:
  selector:
    matchLabels:
      app: go-gin
  replicas: 3
  template:
    metadata:
      labels:
        app: go-gin
    spec:
      containers:
        - name: go-app
          image: vitohuang852/server-service
          imagePullPolicy: Always
          ports:
            - containerPort: 1231

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: "TCP"
      port: 50052
      targetPort: 50052
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  selector:
    matchLabels:
      app: user-service
  replicas: 1
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-app
          image: vitohuang852/user-service
          imagePullPolicy: Always
          ports:
            - containerPort: 50052

---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service
  ports:
    - protocol: "TCP"
      port: 50053
      targetPort: 50053
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  selector:
    matchLabels:
      app: product-service
  replicas: 1
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-app
          image: vitohuang852/product-service
          imagePullPolicy: Always
          ports:
            - containerPort: 50052

---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - protocol: "TCP"
      port: 50054
      targetPort: 50054
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  selector:
    matchLabels:
      app: order-service
  replicas: 1
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-app
          image: vitohuang852/order-service
          imagePullPolicy: Always
          ports:
            - containerPort: 50054

---

