apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    # 選擇帶有 "user-service" 的 pod
    app: user-service
  ports:
    - protocol: "TCP"
      nodePort: 30000
      port: 50052
      targetPort: 50052
  type: NodePort

---
apiVersion: v1
kind: Pod
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  containers:
    - name: user-service-container
      image: vitohuang852/user-service
      imagePullPolicy: Always
      ports:
        - containerPort: 50052
# kubectl apply -f user-service.yaml
# kubectl delete -f user-service.yaml
# minikube service user-service-service --url
